version: '3'
services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 55555
      MYSQL_DATABASE: DB_Thameem
    ports:
      - "3306:3306"
    networks:
      - mynetwork
    volumes:
      - ./int.sql:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: production
    depends_on:
      - db
    networks:
      - mynetwork


networks:
  mynetwork: